## ORDER-SERVICE ##

server:
  port: 9192

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  cloud:
    config:
      uri:
        - http://localhost:9196

logging:
  file: C:/Users/vanma/Desktop/logs/microservice.log


